/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package safPack;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;


/**
 *
 * @author G50
 */
public class safFrame extends javax.swing.JFrame {

    muzyq mz=new muzyq();
    int pX, pY, cpX, cpY, attempo, scorez;
    private static int ball = 1;
    private javax.swing.Timer timer;
    private static int ballxW = 1;
    int y=0,lulu = 0,emmy=10;
    private javax.swing.Timer timerxW;
    private static int ballx = 1;
    private javax.swing.Timer timerx;
    private static int ballZ = 1;
    private javax.swing.Timer timerZ;

    /**
     * Creates new form safFrame
     */
    public safFrame() {
        initComponents();
        playShow.setVisible(false);
        playBut.setVisible(false);
        k1.setVisible(false);
        k2.setVisible(false);
        k3.setVisible(false);
        k4.setVisible(false);
        k5.setVisible(false);
        k6.setVisible(false);
        k7.setVisible(false);
        k8.setVisible(false);
        k9.setVisible(false);
        k10.setVisible(false);
        k11.setVisible(false);
        k12.setVisible(false);
        k13.setVisible(false);
        k14.setVisible(false);
        k15.setVisible(false);
        k16.setVisible(false);
        k17.setVisible(false);
        k18.setVisible(false);
        k19.setVisible(false);
        k20.setVisible(false);
        k21.setVisible(false);
        k22.setVisible(false);
        k23.setVisible(false);
        k24.setVisible(false);
        k25.setVisible(false);
        k26.setVisible(false);
        k27.setVisible(false);
        k28.setVisible(false);
        k29.setVisible(false);
        k30.setVisible(false);
        k31.setVisible(false);
        k32.setVisible(false);
        k33.setVisible(false);
        k34.setVisible(false);
        k35.setVisible(false);
        k36.setVisible(false);
        k37.setVisible(false);
        k38.setVisible(false);
        k39.setVisible(false);
        k40.setVisible(false);
        k41.setVisible(false);
        k42.setVisible(false);
        k43.setVisible(false);
        k44.setVisible(false);
        k45.setVisible(false);
        k46.setVisible(false);
        k47.setVisible(false);
        k48.setVisible(false);
        k49.setVisible(false);
        k50.setVisible(false);
        k51.setVisible(false);
        k52.setVisible(false);
        k53.setVisible(false);
        k54.setVisible(false);
        k55.setVisible(false);
        k56.setVisible(false);
        k57.setVisible(false);
        k58.setVisible(false);
        k59.setVisible(false);
        k60.setVisible(false);
        k61.setVisible(false);
        k62.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        k62 = new javax.swing.JLabel();
        k44 = new javax.swing.JLabel();
        k47 = new javax.swing.JLabel();
        k56 = new javax.swing.JLabel();
        k58 = new javax.swing.JLabel();
        k45 = new javax.swing.JLabel();
        k59 = new javax.swing.JLabel();
        k48 = new javax.swing.JLabel();
        k60 = new javax.swing.JLabel();
        k61 = new javax.swing.JLabel();
        k46 = new javax.swing.JLabel();
        k57 = new javax.swing.JLabel();
        k50 = new javax.swing.JLabel();
        k51 = new javax.swing.JLabel();
        k52 = new javax.swing.JLabel();
        k53 = new javax.swing.JLabel();
        k54 = new javax.swing.JLabel();
        k55 = new javax.swing.JLabel();
        k49 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        k12 = new javax.swing.JLabel();
        k1 = new javax.swing.JLabel();
        k2 = new javax.swing.JLabel();
        k3 = new javax.swing.JLabel();
        k5 = new javax.swing.JLabel();
        k6 = new javax.swing.JLabel();
        k7 = new javax.swing.JLabel();
        k8 = new javax.swing.JLabel();
        k9 = new javax.swing.JLabel();
        k10 = new javax.swing.JLabel();
        k11 = new javax.swing.JLabel();
        k4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        k32 = new javax.swing.JLabel();
        k43 = new javax.swing.JLabel();
        k42 = new javax.swing.JLabel();
        k41 = new javax.swing.JLabel();
        k39 = new javax.swing.JLabel();
        k38 = new javax.swing.JLabel();
        k37 = new javax.swing.JLabel();
        k36 = new javax.swing.JLabel();
        k35 = new javax.swing.JLabel();
        k34 = new javax.swing.JLabel();
        k33 = new javax.swing.JLabel();
        k40 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        k13 = new javax.swing.JLabel();
        k31 = new javax.swing.JLabel();
        k27 = new javax.swing.JLabel();
        k19 = new javax.swing.JLabel();
        k17 = new javax.swing.JLabel();
        k30 = new javax.swing.JLabel();
        k16 = new javax.swing.JLabel();
        k26 = new javax.swing.JLabel();
        k15 = new javax.swing.JLabel();
        k14 = new javax.swing.JLabel();
        k28 = new javax.swing.JLabel();
        k18 = new javax.swing.JLabel();
        k25 = new javax.swing.JLabel();
        k24 = new javax.swing.JLabel();
        k23 = new javax.swing.JLabel();
        k22 = new javax.swing.JLabel();
        k21 = new javax.swing.JLabel();
        k20 = new javax.swing.JLabel();
        k29 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        but1 = new javax.swing.JLabel();
        canII = new javax.swing.JLabel();
        canIII = new javax.swing.JLabel();
        canI = new javax.swing.JLabel();
        remark = new javax.swing.JLabel();
        attempts = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        pal = new javax.swing.JLabel();
        playBut = new javax.swing.JLabel();
        playShow = new javax.swing.JLabel();
        sema = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("\"Animation for a better world\"    Lericks Developers ");
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        k62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel1.add(k62, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 32));

        k44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel1.add(k44, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 30, 32));

        k47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel1.add(k47, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 30, 32));

        k56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel1.add(k56, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 30, 32));

        k58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel1.add(k58, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 30, 32));

        k45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel1.add(k45, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 30, 32));

        k59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel1.add(k59, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 30, 32));

        k48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel1.add(k48, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 30, 32));

        k60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel1.add(k60, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 30, 32));

        k61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel1.add(k61, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 30, 32));

        k46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel1.add(k46, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 30, 32));

        k57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel1.add(k57, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 30, 32));

        k50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel1.add(k50, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 30, 32));

        k51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel1.add(k51, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 30, 32));

        k52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel1.add(k52, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 30, 32));

        k53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel1.add(k53, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 30, 32));

        k54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel1.add(k54, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 30, 32));

        k55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel1.add(k55, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 30, 32));

        k49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel1.add(k49, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 30, 32));

        jLayeredPane1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 860, 50));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        k12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel2.add(k12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 30, 32));

        k1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel2.add(k1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 30, 32));

        k2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel2.add(k2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 30, 32));

        k3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel2.add(k3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 30, 32));

        k5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel2.add(k5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 30, 32));

        k6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel2.add(k6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 30, 32));

        k7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel2.add(k7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 30, 32));

        k8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel2.add(k8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 30, 32));

        k9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel2.add(k9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 30, 32));

        k10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel2.add(k10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 30, 32));

        k11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel2.add(k11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 30, 32));

        k4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel2.add(k4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 30, 32));

        jLayeredPane1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 580));

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        k32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel3.add(k32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 30, 32));

        k43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel3.add(k43, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 30, 40));

        k42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel3.add(k42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 30, 32));

        k41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel3.add(k41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 30, 32));

        k39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel3.add(k39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 30, 32));

        k38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel3.add(k38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 30, 32));

        k37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel3.add(k37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 30, 32));

        k36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel3.add(k36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 30, 32));

        k35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel3.add(k35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 30, 32));

        k34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel3.add(k34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 30, 32));

        k33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel3.add(k33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 30, 32));

        k40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel3.add(k40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 30, 32));

        jLayeredPane1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 30, 580));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        k13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel4.add(k13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 32));

        k31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel4.add(k31, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 30, 32));

        k27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel4.add(k27, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 30, 32));

        k19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel4.add(k19, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 30, 32));

        k17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel4.add(k17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 30, 32));

        k30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel4.add(k30, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 30, 32));

        k16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel4.add(k16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 30, 32));

        k26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel4.add(k26, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 30, 32));

        k15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel4.add(k15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 30, 32));

        k14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel4.add(k14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 30, 32));

        k28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel4.add(k28, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 30, 32));

        k18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel4.add(k18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 30, 32));

        k25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel4.add(k25, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 30, 32));

        k24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel4.add(k24, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 30, 32));

        k23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel4.add(k23, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 30, 32));

        k22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel4.add(k22, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 30, 32));

        k21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel4.add(k21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 30, 32));

        k20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel4.add(k20, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 30, 32));

        k29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safRed - Copy.png"))); // NOI18N
        jPanel4.add(k29, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 30, 32));

        jLayeredPane1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 860, 40));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        but1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                but1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                but1MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                but1MouseReleased(evt);
            }
        });
        jPanel5.add(but1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 120, 20));

        canII.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ratPack/green.png"))); // NOI18N
        canII.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                canIIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                canIIMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                canIIMouseReleased(evt);
            }
        });
        jPanel5.add(canII, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 120, 230));

        canIII.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ratPack/purple.png"))); // NOI18N
        canIII.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                canIIIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                canIIIMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                canIIIMouseReleased(evt);
            }
        });
        jPanel5.add(canIII, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, 120, 230));

        canI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ratPack/black.png"))); // NOI18N
        canI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                canIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                canIMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                canIMouseReleased(evt);
            }
        });
        jPanel5.add(canI, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 120, 230));

        remark.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        remark.setText("Remark: Find rats");
        jPanel5.add(remark, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 190, 30));

        attempts.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        attempts.setForeground(new java.awt.Color(51, 0, 51));
        attempts.setText("Attempts: 0");
        jPanel5.add(attempts, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 200, 30));

        score.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        score.setForeground(new java.awt.Color(0, 0, 153));
        score.setText("Score: 0");
        jPanel5.add(score, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 200, 40));

        pal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ratPack/how.png"))); // NOI18N
        jPanel5.add(pal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 430, 470));

        playBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                playButMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                playButMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                playButMouseReleased(evt);
            }
        });
        jPanel5.add(playBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 200, 40));

        playShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ratPack/play.png"))); // NOI18N
        jPanel5.add(playShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 330, 80));

        sema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ratPack/back.png"))); // NOI18N
        jPanel5.add(sema, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 480));

        jLayeredPane1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 860, 480));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setOpaque(true);
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void green() {
    new Thread(){
       @Override
   public void run(){
        timerx = new javax.swing.Timer(100, new ActionListener() {
            public void actionPerformed(ActionEvent ae) {
                switch (ballx) {
                    case 1:

                        k1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png"))); // NOI18N

                        break;
                    case 2:

                        k2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 3:

                        k3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 4:

                        k4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 5:

                        k5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 6:

                        k6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 7:

                        k7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 8:

                        k8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 9:

                        k9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 10:

                        k10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 11:

                        k11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 12:

                        k12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 13:

                        k13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 14:

                        k14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 15:

                        k15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 16:

                        k16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 17:

                        k17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 18:

                        k18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 19:

                        k19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 20:

                        k20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png"))); // NOI18N

                        break;
                    case 21:

                        k21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 22:

                        k22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 23:

                        k23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 24:

                        k24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 25:

                        k25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 26:

                        k26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 27:

                        k27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 28:

                        k28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 29:

                        k29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 30:

                        k30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 31:

                        k31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png"))); // NOI18N

                        break;
                    case 32:

                        k32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 33:

                        k33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 34:

                        k34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 35:

                        k35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 36:

                        k36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 37:

                        k37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 38:

                        k38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 39:

                        k39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 40:

                        k40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 41:

                        k41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png"))); // NOI18N

                        break;
                    case 42:

                        k42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 43:

                        k43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 44:

                        k44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 45:

                        k45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 46:

                        k46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 47:

                        k47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 48:

                        k48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 49:

                        k49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 50:

                        k50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 51:

                        k51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png"))); // NOI18N

                        break;
                    case 52:

                        k52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 53:

                        k53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 54:

                        k54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 55:

                        k55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 56:

                        k56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 57:

                        k57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 58:

                        k58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 59:

                        k59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 60:

                        k60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 61:

                        k61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                    case 62:

                        k62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safGreen_Copy.png")));
                        break;
                }
                if (ballx == 62) {
                    ballx = 0;
                    y = y + 1;
                    if (y == 5) {
                        showNon();
                        y = 0;
                    }

                }
                ballx++;
            }
        });
        timerx.start();
   }}.start();

    }

    public void white() {
//"/safPack/safWhite - Copy.png"
        new Thread(){
       @Override
   public void run(){
        timerxW = new javax.swing.Timer(100, new ActionListener() {
            public void actionPerformed(ActionEvent ae) {
                switch (ballxW) {
                    case 1:

                        k1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png"))); // NOI18N

                        break;
                    case 2:

                        k2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 3:

                        k3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 4:

                        k4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 5:

                        k5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 6:

                        k6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 7:

                        k7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 8:

                        k8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 9:

                        k9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 10:

                        k10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 11:

                        k11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 12:

                        k12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 13:

                        k13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 14:

                        k14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 15:

                        k15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 16:

                        k16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 17:

                        k17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 18:

                        k18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 19:

                        k19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 20:

                        k20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png"))); // NOI18N

                        break;
                    case 21:

                        k21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 22:

                        k22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 23:

                        k23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 24:

                        k24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 25:

                        k25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 26:

                        k26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 27:

                        k27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 28:

                        k28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 29:

                        k29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 30:

                        k30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 31:

                        k31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png"))); // NOI18N

                        break;
                    case 32:

                        k32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 33:
                        k33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 34:

                        k34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 35:

                        k35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 36:

                        k36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 37:

                        k37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 38:

                        k38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 39:

                        k39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 40:

                        k40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 41:

                        k41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png"))); // NOI18N

                        break;
                    case 42:

                        k42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 43:

                        k43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 44:

                        k44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 45:

                        k45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 46:

                        k46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 47:

                        k47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 48:

                        k48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 49:

                        k49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 50:

                        k50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 51:

                        k51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png"))); // NOI18N

                        break;
                    case 52:

                        k52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 53:

                        k53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 54:

                        k54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 55:

                        k55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 56:

                        k56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 57:

                        k57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 58:

                        k58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 59:

                        k59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 60:

                        k60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 61:

                        k61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                    case 62:

                        k62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safPack/safWhite - Copy.png")));
                        break;
                }
                if (ballxW == 62) {
                    ballxW = 0;
                    green();

                }
                ballxW++;
            }
        });
        timerxW.start();
   }}.start();
    }

    public void showAll() {
        new Thread(){
       @Override
   public void run(){
        timerZ = new javax.swing.Timer(100, new ActionListener() {
            public void actionPerformed(ActionEvent ae) {
                switch (ballZ) {
                    case 1:
                        k1.setVisible(true);

                        break;
                    case 2:
                        k2.setVisible(true);

                        break;
                    case 3:
                        k3.setVisible(true);

                        break;
                    case 4:
                        k4.setVisible(true);

                        break;
                    case 5:
                        k5.setVisible(true);

                        break;
                    case 6:
                        k6.setVisible(true);

                        break;
                    case 7:
                        k7.setVisible(true);

                        break;
                    case 8:
                        k8.setVisible(true);

                        break;
                    case 9:
                        k9.setVisible(true);

                        break;
                    case 10:
                        k10.setVisible(true);

                        break;
                    case 11:
                        k11.setVisible(true);

                        break;
                    case 12:
                        k12.setVisible(true);

                        break;
                    case 13:

                        k13.setVisible(true);

                        break;
                    case 14:
                        k14.setVisible(true);

                        break;
                    case 15:
                        k15.setVisible(true);

                        break;
                    case 16:
                        k16.setVisible(true);

                        break;
                    case 17:
                        k17.setVisible(true);

                        break;
                    case 18:
                        k18.setVisible(true);

                        break;
                    case 19:
                        k19.setVisible(true);

                        break;
                    case 20:
                        k20.setVisible(true);

                        break;

                    case 21:
                        k21.setVisible(true);

                        break;
                    case 22:
                        k22.setVisible(true);

                        break;
                    case 23:
                        k23.setVisible(true);

                        break;
                    case 24:
                        k24.setVisible(true);

                        break;
                    case 25:
                        k25.setVisible(true);

                        break;
                    case 26:
                        k26.setVisible(true);

                        break;
                    case 27:
                        k27.setVisible(true);

                        break;
                    case 28:
                        k28.setVisible(true);

                        break;
                    case 29:
                        k29.setVisible(true);

                        break;
                    case 30:
                        k30.setVisible(true);

                        break;
                    case 31:
                        k31.setVisible(true);

                        break;
                    case 32:
                        k32.setVisible(true);

                        break;
                    case 33:
                        k33.setVisible(true);

                        break;
                    case 34:
                        k34.setVisible(true);

                        break;
                    case 35:
                        k35.setVisible(true);

                        break;
                    case 36:
                        k36.setVisible(true);

                        break;
                    case 37:
                        k37.setVisible(true);

                        break;
                    case 38:
                        k38.setVisible(true);

                        break;
                    case 39:
                        k39.setVisible(true);

                        break;
                    case 40:
                        k40.setVisible(true);

                        break;
                    case 41:
                        k41.setVisible(true);

                        break;
                    case 42:
                        k42.setVisible(true);

                        break;
                    case 43:
                        k43.setVisible(true);

                        break;
                    case 44:
                        k44.setVisible(true);

                        break;
                    case 45:
                        k45.setVisible(true);

                        break;
                    case 46:
                        k46.setVisible(true);

                        break;
                    case 47:
                        k47.setVisible(true);

                        break;
                    case 48:
                        k48.setVisible(true);

                        break;
                    case 49:
                        k49.setVisible(true);

                        break;
                    case 50:
                        k50.setVisible(true);

                        break;
                    case 51:
                        k51.setVisible(true);

                        break;
                    case 52:
                        k52.setVisible(true);

                        break;
                    case 53:
                        k53.setVisible(true);

                        break;
                    case 54:
                        k54.setVisible(true);

                        break;
                    case 55:
                        k55.setVisible(true);

                        break;
                    case 56:
                        k56.setVisible(true);

                        break;
                    case 57:
                        k57.setVisible(true);

                        break;
                    case 58:
                        k58.setVisible(true);

                        break;
                    case 59:
                        k59.setVisible(true);

                        break;
                    case 60:
                        k60.setVisible(true);

                        break;
                    case 61:
                        k61.setVisible(true);

                        break;
                    case 62:
                        k62.setVisible(true);

                        break;
                }

                if (ballZ == 62) {
                    ballZ = 0;
                    green();

                }
                ballZ++;
            }
        });
        timerZ.start();
   }}.start();
    }
    public void showNon() {
        
        k1.setVisible(false);
        k2.setVisible(false);
        k3.setVisible(false);
        k4.setVisible(false);
        k5.setVisible(false);
        k6.setVisible(false);
        k7.setVisible(false);
        k8.setVisible(false);
        k9.setVisible(false);
        k10.setVisible(false);
        k11.setVisible(false);
        k12.setVisible(false);
        k13.setVisible(false);
        k14.setVisible(false);
        k15.setVisible(false);
        k16.setVisible(false);
        k17.setVisible(false);
        k18.setVisible(false);
        k19.setVisible(false);
        k20.setVisible(false);
        k21.setVisible(false);
        k22.setVisible(false);
        k23.setVisible(false);
        k24.setVisible(false);
        k25.setVisible(false);
        k26.setVisible(false);
        k27.setVisible(false);
        k28.setVisible(false);
        k29.setVisible(false);
        k30.setVisible(false);
        k31.setVisible(false);
        k32.setVisible(false);
        k33.setVisible(false);
        k34.setVisible(false);
        k35.setVisible(false);
        k36.setVisible(false);
        k37.setVisible(false);
        k38.setVisible(false);
        k39.setVisible(false);
        k40.setVisible(false);
        k41.setVisible(false);
        k42.setVisible(false);
        k43.setVisible(false);
        k44.setVisible(false);
        k45.setVisible(false);
        k46.setVisible(false);
        k47.setVisible(false);
        k48.setVisible(false);
        k49.setVisible(false);
        k50.setVisible(false);
        k51.setVisible(false);
        k52.setVisible(false);
        k53.setVisible(false);
        k54.setVisible(false);
        k55.setVisible(false);
        k56.setVisible(false);
        k57.setVisible(false);
        k58.setVisible(false);
        k59.setVisible(false);
        k60.setVisible(false);
        k61.setVisible(false);
        k62.setVisible(false);
        showAll();
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        new Thread(){
       @Override
   public void run(){
        timer = new javax.swing.Timer(100, new ActionListener() {
            public void actionPerformed(ActionEvent ae) {
                switch (ball) {
                    case 1:
                        k1.setVisible(true);

                        break;
                    case 2:
                        k2.setVisible(true);

                        break;
                    case 3:
                        k3.setVisible(true);

                        break;
                    case 4:
                        k4.setVisible(true);

                        break;
                    case 5:
                        k5.setVisible(true);

                        break;
                    case 6:
                        k6.setVisible(true);

                        break;
                    case 7:
                        k7.setVisible(true);

                        break;
                    case 8:
                        k8.setVisible(true);

                        break;
                    case 9:
                        k9.setVisible(true);

                        break;
                    case 10:
                        k10.setVisible(true);

                        break;
                    case 11:
                        k11.setVisible(true);

                        break;
                    case 12:
                        k12.setVisible(true);

                        break;
                    case 13:

                        k13.setVisible(true);

                        break;
                    case 14:
                        k14.setVisible(true);

                        break;
                    case 15:
                        k15.setVisible(true);

                        break;
                    case 16:
                        k16.setVisible(true);

                        break;
                    case 17:
                        k17.setVisible(true);

                        break;
                    case 18:
                        k18.setVisible(true);

                        break;
                    case 19:
                        k19.setVisible(true);

                        break;
                    case 20:
                        k20.setVisible(true);

                        break;

                    case 21:
                        k21.setVisible(true);

                        break;
                    case 22:
                        k22.setVisible(true);

                        break;
                    case 23:
                        k23.setVisible(true);

                        break;
                    case 24:
                        k24.setVisible(true);

                        break;
                    case 25:
                        k25.setVisible(true);

                        break;
                    case 26:
                        k26.setVisible(true);

                        break;
                    case 27:
                        k27.setVisible(true);

                        break;
                    case 28:
                        k28.setVisible(true);

                        break;
                    case 29:
                        k29.setVisible(true);

                        break;
                    case 30:
                        k30.setVisible(true);

                        break;
                    case 31:
                        k31.setVisible(true);

                        break;
                    case 32:
                        k32.setVisible(true);

                        break;
                    case 33:
                        k33.setVisible(true);

                        break;
                    case 34:
                        k34.setVisible(true);

                        break;
                    case 35:
                        k35.setVisible(true);

                        break;
                    case 36:
                        k36.setVisible(true);

                        break;
                    case 37:
                        k37.setVisible(true);

                        break;
                    case 38:
                        k38.setVisible(true);

                        break;
                    case 39:
                        k39.setVisible(true);

                        break;
                    case 40:
                        k40.setVisible(true);

                        break;
                    case 41:
                        k41.setVisible(true);

                        break;
                    case 42:
                        k42.setVisible(true);

                        break;
                    case 43:
                        k43.setVisible(true);

                        break;
                    case 44:
                        k44.setVisible(true);

                        break;
                    case 45:
                        k45.setVisible(true);

                        break;
                    case 46:
                        k46.setVisible(true);

                        break;
                    case 47:
                        k47.setVisible(true);

                        break;
                    case 48:
                        k48.setVisible(true);

                        break;
                    case 49:
                        k49.setVisible(true);

                        break;
                    case 50:
                        k50.setVisible(true);

                        break;
                    case 51:
                        k51.setVisible(true);

                        break;
                    case 52:
                        k52.setVisible(true);

                        break;
                    case 53:
                        k53.setVisible(true);

                        break;
                    case 54:
                        k54.setVisible(true);

                        break;
                    case 55:
                        k55.setVisible(true);

                        break;
                    case 56:
                        k56.setVisible(true);

                        break;
                    case 57:
                        k57.setVisible(true);

                        break;
                    case 58:
                        k58.setVisible(true);

                        break;
                    case 59:
                        k59.setVisible(true);

                        break;
                    case 60:
                        k60.setVisible(true);

                        break;
                    case 61:
                        k61.setVisible(true);

                        break;
                    case 62:
                        k62.setVisible(true);

                        break;
                }

                if (ball == 62) {
                    ball = 0;
                    white();

                }
                ball++;
            }
        });
        timer.start();
   }}.start();
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void but1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but1MouseEntered
        sema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ratPack/backSelect.png"))); // NOI18N
    }//GEN-LAST:event_but1MouseEntered

    private void but1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but1MouseExited
        sema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ratPack/back.png"))); // NOI18N     
    }//GEN-LAST:event_but1MouseExited

    private void but1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but1MouseReleased
        System.exit(0);
    }//GEN-LAST:event_but1MouseReleased

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        pX = evt.getX();
        pY = evt.getY();
        // TODO add your handling code here:
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - pX, this.getLocation().y + evt.getY() - pY);
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseDragged

    private void canIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canIMouseEntered
        if(lulu==0){
        canI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ratPack/blackSelect.png")));
        }
    }//GEN-LAST:event_canIMouseEntered

    private void canIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canIMouseExited
        if(lulu==0){
        canI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ratPack/black.png"))); // NOI18N
        }
    }//GEN-LAST:event_canIMouseExited

    private void canIIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canIIMouseEntered
       if(lulu==0){
        canII.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ratPack/greenSelect.png"))); // NOI18N
       }
    }//GEN-LAST:event_canIIMouseEntered

    private void canIIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canIIMouseExited
        if(lulu==0){
        canII.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ratPack/green.png"))); // NOI18N
        }
    }//GEN-LAST:event_canIIMouseExited

    private void canIIIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canIIIMouseEntered
        if(lulu==0){
        canIII.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ratPack/purpleSelect.png"))); // NOI18N
        }
    }//GEN-LAST:event_canIIIMouseEntered

    private void canIIIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canIIIMouseExited
        if(lulu==0){
        canIII.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ratPack/purple.png"))); // NOI18N
        }
    }//GEN-LAST:event_canIIIMouseExited

    private void canIMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canIMouseReleased
if(emmy==10){
        new Thread(){
       @Override
   public void run(){
   playShow.setVisible(true);
   emmy=20;
        playBut.setVisible(true);
        attempo += 1;
        attempts.setText("Attempts: " + attempo);
        Random tasha = new Random();
        int lerick = tasha.nextInt(3);
        if (lerick == 0) {
            canI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ratPack/blackRat.png")));
            scorez += 5;
            score.setText("Score: " + scorez);
            remark.setText("Remark: Excellent");
            canII.setVisible(false);
            canIII.setVisible(false);
        } else if (lerick == 1) {
            remark.setText("Remark: Sorry");
            canI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ratPack/blackNoRat.png")));
            canII.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ratPack/greenRat.png")));
            canIII.setVisible(false);
        } else if (lerick == 2) {
            remark.setText("Remark: Sorry");
            canI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ratPack/blackNoRat.png")));
            canIII.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ratPack/purpleRat.png")));
            canII.setVisible(false);

        }
        lulu=20;
        
   }
   }.start();
        
}
    }//GEN-LAST:event_canIMouseReleased

    private void canIIMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canIIMouseReleased
      if(emmy==10){
        new Thread(){
       @Override
   public void run(){
       emmy=20;
        playShow.setVisible(true);
        playBut.setVisible(true);
        attempo += 1;
        attempts.setText("Attempts: " + attempo);
        Random tasha = new Random();
        int lerick = tasha.nextInt(3);
        if (lerick == 0) {
            canI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ratPack/blackRat.png")));
            remark.setText("Remark: Sorry");
            canII.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ratPack/greenNoRat.png")));
            canIII.setVisible(false);
        } else if (lerick == 1) {
            remark.setText("Remark: Excellent");
            scorez += 5;
            score.setText("Scores: " + scorez);
            canII.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ratPack/greenRat.png")));
            canI.setVisible(false);
            canIII.setVisible(false);
        } else if (lerick == 2) {
            remark.setText("Remark: Sorry");
            canIII.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ratPack/purpleRat.png")));
            canII.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ratPack/greenNoRat.png")));
            canI.setVisible(false);

        }
        lulu=20;
       
         }
   }.start(); 
      }   
    }//GEN-LAST:event_canIIMouseReleased

    private void canIIIMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canIIIMouseReleased
       if(emmy==10){
           new Thread(){
       @Override
   public void run(){
        playShow.setVisible(true);
        emmy=20;
        playBut.setVisible(true);
        attempo += 1;
        attempts.setText("Attempts: " + attempo);
        Random tasha = new Random();
        int lerick = tasha.nextInt(3);
        if (lerick == 0) {
            canI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ratPack/blackRat.png")));
            remark.setText("Remark: Sorry");
            canIII.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ratPack/purpleNoRat.png")));
            canII.setVisible(false);
        } else if (lerick == 1) {
            remark.setText("Remark: Sorry");
            canII.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ratPack/greenRat.png")));
            canI.setVisible(false);
            canIII.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ratPack/purpleNoRat.png")));
        } else if (lerick == 2) {
            remark.setText("Remark: Excellent");
            scorez += 5;
            score.setText("Scores: " + scorez);
            canIII.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ratPack/purpleRat.png")));
            canII.setVisible(false);
            canI.setVisible(false);

        }
        lulu=20;
       
               }
   }.start();
       }
    }//GEN-LAST:event_canIIIMouseReleased

    private void playButMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playButMouseEntered
        playShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ratPack/playSelect.png"))); // NOI18N
    }//GEN-LAST:event_playButMouseEntered

    private void playButMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playButMouseExited
        playShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ratPack/play.png"))); // NOI18N
    }//GEN-LAST:event_playButMouseExited

    private void playButMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playButMouseReleased
       new Thread(){
       @Override
   public void run(){
        canI.setVisible(true);
        canII.setVisible(true);
        canIII.setVisible(true);
        lulu=0;
        emmy=10;
        canI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ratPack/black.png")));
        canII.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ratPack/green.png")));
        canIII.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ratPack/purple.png")));
        canI.setVisible(true);
        canII.setVisible(true);
        canIII.setVisible(true);
        remark.setText("Remark: Find rats");
        playShow.setVisible(false);
        playBut.setVisible(false);
               }
   }.start();
    }//GEN-LAST:event_playButMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(safFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(safFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(safFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(safFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //mz.play("C:\\Users\\G50\\Desktop\\bobbyNocks.mp3");
                new safFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel attempts;
    private javax.swing.JLabel but1;
    private javax.swing.JLabel canI;
    private javax.swing.JLabel canII;
    private javax.swing.JLabel canIII;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel k1;
    private javax.swing.JLabel k10;
    private javax.swing.JLabel k11;
    private javax.swing.JLabel k12;
    private javax.swing.JLabel k13;
    private javax.swing.JLabel k14;
    private javax.swing.JLabel k15;
    private javax.swing.JLabel k16;
    private javax.swing.JLabel k17;
    private javax.swing.JLabel k18;
    private javax.swing.JLabel k19;
    private javax.swing.JLabel k2;
    private javax.swing.JLabel k20;
    private javax.swing.JLabel k21;
    private javax.swing.JLabel k22;
    private javax.swing.JLabel k23;
    private javax.swing.JLabel k24;
    private javax.swing.JLabel k25;
    private javax.swing.JLabel k26;
    private javax.swing.JLabel k27;
    private javax.swing.JLabel k28;
    private javax.swing.JLabel k29;
    private javax.swing.JLabel k3;
    private javax.swing.JLabel k30;
    private javax.swing.JLabel k31;
    private javax.swing.JLabel k32;
    private javax.swing.JLabel k33;
    private javax.swing.JLabel k34;
    private javax.swing.JLabel k35;
    private javax.swing.JLabel k36;
    private javax.swing.JLabel k37;
    private javax.swing.JLabel k38;
    private javax.swing.JLabel k39;
    private javax.swing.JLabel k4;
    private javax.swing.JLabel k40;
    private javax.swing.JLabel k41;
    private javax.swing.JLabel k42;
    private javax.swing.JLabel k43;
    private javax.swing.JLabel k44;
    private javax.swing.JLabel k45;
    private javax.swing.JLabel k46;
    private javax.swing.JLabel k47;
    private javax.swing.JLabel k48;
    private javax.swing.JLabel k49;
    private javax.swing.JLabel k5;
    private javax.swing.JLabel k50;
    private javax.swing.JLabel k51;
    private javax.swing.JLabel k52;
    private javax.swing.JLabel k53;
    private javax.swing.JLabel k54;
    private javax.swing.JLabel k55;
    private javax.swing.JLabel k56;
    private javax.swing.JLabel k57;
    private javax.swing.JLabel k58;
    private javax.swing.JLabel k59;
    private javax.swing.JLabel k6;
    private javax.swing.JLabel k60;
    private javax.swing.JLabel k61;
    private javax.swing.JLabel k62;
    private javax.swing.JLabel k7;
    private javax.swing.JLabel k8;
    private javax.swing.JLabel k9;
    private javax.swing.JLabel pal;
    private javax.swing.JLabel playBut;
    private javax.swing.JLabel playShow;
    private javax.swing.JLabel remark;
    private javax.swing.JLabel score;
    private javax.swing.JLabel sema;
    // End of variables declaration//GEN-END:variables
}
